### ISSUE TITLE
Make 'greensfunctions' parameter functional

### ISSUE THREAD

**Issue by CTrabant** [iris-edu/irisws-syngine#1]
This option requires plumbing to backend Instaseis servers.

**Comment by alexhutko** [comment]
Hi @krischer, let us know when this is supported in the instaseis servers and we'll support it in syngine.
thanks

**Comment by krischer** [comment]
The instaseis server gained support for this like half a year ago: http://instaseis.net/routes/greens_function.html

Please not that the source-receiver geometry for this route is given in epicentral distance and event depth in spherical coordinates. I'm not entirely sure if it is sensible to map this to lat/lng coordinates but it is also not wrong so the choice is up to you.

**Comment by manoch-iris** [comment]
The functionality was rolled in by installation of Instaseis 1.1.0
