### ISSUE TITLE
Forwarding Custom Header Field?

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#10]
Hi guys,

would you consider forwarding a custom header field from the instaseis server? It is only about the `Instaseis-Mu` header - it is currently not set by the `/seismograms` route but only by the `/seisomograms_raw` route. If you agree to forward it I will add it to the `/seismograms` route for requests where it makes sense.

This might be useful for people who want to use syngine for their own finite sources (not the USGS param files). This is a very niche use case but something to maybe think about.

**Comment by CTrabant** [comment]
In principle forwarding such a header would be fine.  The current software stack does not allow this, unfortunately.  The general issue is allowing the "handler" portion of the middleware being able set HTTP headers.  We need this to be able to set the Content-Disposition header according to the label.  When we figure out how passing on the `Instaseis-Mu` header should be straightforward.

**Comment by CTrabant** [comment]
Done.  The `Instaseis-Mu` header from the first request to an Istaseis backend is included in the HTTP headers from the syngine service.  Note that the case gets converted to lower, e.g. the header comes out `instaseis-mu`, most likely by Tomcat (out of our control).  But HTTP headers are defined as case insensitive, so they are equivalent.

**Comment by krischer** [comment]
Thanks! Works with the Instaseis syngine client as of krischer/instaseis@049bbcd6ef521159710cd5f3b07d9bb70223960e
