### ISSUE TITLE
Status of database computations

### ISSUE THREAD

**Issue by sstaehler** [iris-edu/irisws-syngine#12]
Just to keep you updated:
- [x] AK135f 1s period, 1800 s duration, vertical only
- [x] AK135f 2s period, 3600 s duration
- [x] prem_iso  2s period, 3600 s duration
- [ ] PREM continential crust 2s period, 3600 s duration
- [ ] PREM oceanic crust 2s period, 3600 s duration
- [x] PREM 5s, 3600 s duration for the FFM service 
- [x] PREM 10 s resolution, 18000 s duration for large earthquake coda studies

**Comment by krischer** [comment]
I think it has only upsides if we replace `AK135f 1s period, 1800 s duration, vertical only` with `AK135f 1s period, 3600 s duration, all components, only 100 km source depth`.

Disc requirements should be fairly similar to the 2s databases.

@alexhutko, @CTrabant What do you think?

**Comment by alexhutko** [comment]
What kind of use cases would benefit from 1s vs 2s horizontal components?   I'm not sure I see that as a big win at the expense of no deep sources.

**Comment by sstaehler** [comment]
Having given it a second thought, I would also rather have the full-depth, vertical only-database. 

You can't study much more than P-waves at 1s anyway and there, deep events might be of interest.

**Comment by CTrabant** [comment]
> Having given it a second thought, I would also rather have the full-depth, vertical only-database.
> 
> You can't study much more than P-waves at 1s anyway and there, deep events might be of interest.
> 
> In Seattle we are also leaning towards full depth range.

Chad

**Comment by krischer** [comment]
:+1: That sounds very reasonable - I am convinced. Sorry for the confusion.

**Comment by sstaehler** [comment]
SuperMUC is down again...

**Comment by krischer** [comment]
@alexhutko @CTrabant Do you want the hard disc delivered via FedEx or is it enough if I just bring them to AGU?

**Comment by sstaehler** [comment]
@krischer and I found that the waveforms for the PREM_oceanic and PREM_continental models seem buggy. Especially the amplitudes on the horizontal components are much too high (20 orders of magnitude). We assume that the high velocity contrasts in the uppermost layers are a bigger problem than assumed, even though we (as in "the AxiSEM developers") do not understand yet, why.

I would propose to release the product without these models and add them at a later stage in a well-tested manner.

**Comment by alexhutko** [comment]
That sounds fine.  They're listed as "coming soon" on our webpage, which is nice and ambiguous.
