### ISSUE TITLE
Maximum depth of databases?

### ISSUE THREAD

**Issue by sstaehler** [iris-edu/irisws-syngine#13]
@CTrabant Testing the 5s database (for Finite-Fault solutions) against the deep Okhotsk earthquake, I noticed that its fault plane has a maximum depth of 720 km.
http://earthquake.usgs.gov/earthquakes/eventpage/usb000h4jh#scientific_finitefault

So far, I assumed that 700 km maximum depth would be enough. Shall I increase that to 750 km for all models? This event is unique with respect to depth and magnitude, but it may not be the last one.

**Comment by CTrabant** [comment]
As long as it does not significantly change the time required to calculate or the database volume, yes, increase all of the to 750km.
