### ISSUE TITLE
ObsPy Tutorial?

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#16]
There is a small SAC tutorial here: http://ds.iris.edu/ds/products/syngine/

Would you consider also adding an ObsPy version of the same thing if I provide it?

**Comment by CTrabant** [comment]
Most definitely.  Thanks for the offer.

**Comment by alexhutko** [comment]
Does this tutorial already exist somewhere so we can include it before releasing in the next few days?
related to: https://github.com/iris-edu/irisws-syngine/issues/17

**Comment by krischer** [comment]
I just made it - you can find it here: http://nbviewer.ipython.org/gist/krischer/3e655576e4d17e6c95f2

Let me know if you require a different format or some other changes. I tried to keep it very simple and basic - thus no convolution and other complexities. The fit between data and synthetics (especially the amplitude) is quite good! The event (I used the same you used for the SAC tutorial) really only produces usable body waves.

We could also add a live version of that notebook here: http://krischer.github.io/seismo_live/

BTW and totally off-topic: I would be incredibly useful if IRIS offers a way to run these notebooks at the DMC - users would no longer need to download data but can work where the data is. More info here: http://jupyter.org/
Are there any plans for something along these lines? I feel like that would greatly benefit the community and is a direction we should move towards.

**Comment by alexhutko** [comment]
1) Thanks for the notebook.
2) Thanks for the excellent DMC notebook idea.  We'll definitely think about ways for us go in this direction.

**Comment by CTrabant** [comment]
> BTW and totally off-topic: I would be incredibly useful if IRIS offers a way to run these > notebooks at the DMC - users would no longer need to download data but can work where the > data is. More info here: http://jupyter.org/
> Are there any plans for something along these lines? I feel like that would greatly
> benefit the community and is a direction we should move towards.

I have investigated and dreamed about this for years, no exaggeration.  I think we've spoken about it before.  The main issues are resources, user resource limits and, to some degree, user accounts.  I've looked at Jupyter before, maybe it has come along more to help with those issues.  To do it well would take some real work and commitment even if Jupyter takes care of many details.

The other side of "work where the data is" means the DMC needs to host many peoples data copies and processing resources.  That is no small burden.  Unless it's limited to small CPU and storage, making it less useful, the burden could be huge.  The reality is that, collectively, DMC users have much more CPU and storage; distributed computing of a sort.

This remains high on my list though, even if it started small I think it could be very useful.  I'll take another look at Jupyter.

----- Original Message -----

**Comment by krischer** [comment]
I realize this is something that takes significant dedication and is a huge effort but I strongly believe it's worth it.

> I'll take another look at Jupyter.

They acquired quite a ridiculous amount of funding in the last year and are heavily pushing towards central deployments with user accounts and what not.

There is a ton more to say about this topic but let's just chat at AGU!

**Comment by CTrabant** [comment]
Posted as part of the documentation, thanks for the contribution.
