### ISSUE TITLE
Convolution issue in the SAC tutorial

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#17]
The SAC tutorial (http://ds.iris.edu/ds/products/syngine) convolves with a triangular source time function. There are two(three) issue with the current approach:
1. A triangle is not bandlimited and will thus introduce frequencies into the seismogram that have not been simulated. The effect is likely not that big in many cases but as this is the tutorial on the official syngine page it should be correct as many people will just copy-paste. Better to use some gaussian that approximates a triangle.
2. You will also have to deconvolve the existing source time function of the database otherwise you end up with both being convolved at the same time. As this is not a stable operation you will have to "reconvolve", e.g. deconvolve with the database STF and convolve with a new one at the same time.
3. I am not fully sure how the convolution is implemented in SAC but their documentation seems to say that convolution does not correct for any time shift. In that case it will introduce a time shift on the synthetics of half the length of the triangle. You would have to correct for that if my interpretation of SAC's doc is correct.

I think a tutorial on the syngine page should be as correct as possible as many people will probably assume just that.

**Comment by alexhutko** [comment]
Thanks for catching this.  

1) SAC is very standard and familiar to the community, but limited; it doesn't offer gaussians in the function generate (fg) command.

2) Would using the greens_function take care of this?

3) Yes.

An obspy tutorial will help.  Hopefully one day we could integrate that into a client side python fetch script.

**Comment by chad-earthscope** [comment]
Tutorial updated.
