### ISSUE TITLE
syngine feature freeze

### ISSUE THREAD

**Issue by alexhutko** [iris-edu/irisws-syngine#19]
Hi all,
We'd like to have a feature freeze by the end of htis week.  Are there any features being developed/modified at this point?

thanks,
Alex

**Comment by krischer** [comment]
Hi Alex,

the only not-yet-implemented candidate I can think of is the custom source time function in krischer/instaseis#21

The finite source route has already been ready for quite a while and would be great if it can be included as its completely done on Instaseis' side and you only need to relay it in your middleware: http://instaseis.net/routes/finite_source.html

Cheers!

Lion

**Comment by chad-earthscope** [comment]
Syngine 1.0 is released.
