### ISSUE TITLE
make syngine default = isotropic explosive source?

### ISSUE THREAD

**Issue by alexhutko** [iris-edu/irisws-syngine#20]
Hi,

Right now instaseis requires a source input.  We think for syngine it might be good to have a default source for users who just want some wiggles and don't care about the moment tensor.  Yes, real seismologists can put in a source themselves, but maybe not undergraduate students.

Thoughts?  Is there something I'm not considering?

I'd propose something like a M6.5ish isotropic point-source:
Mrr=1e19
Mtt=1e19
Mpp=1e19
Mrt=Mtp=Mrp = 0

Thanks,
Alex

**Comment by tnissen** [comment]
I'd probably opt for a Mrr (i.e. all other components zero) source as that includes direct S-waves... but is still fairly simple (a monopole radiation).

**Comment by sstaehler** [comment]
I would propose to have a pure Mrr source. The big advantage is that it 
creates S-waves as well and is still isotropic, so for each azimuth, you 
get all wave types.

**Comment by alexhutko** [comment]
Yes of course.  Thanks gang.
Alex

**Comment by sstaehler** [comment]
There is a German saying for this situation...

**Comment by martinvandriel** [comment]
dict.cc translates it as "Great minds think alike." Or "Fools seldom differ." Your choice.

**Comment by CTrabant** [comment]
Pure Mrr source as moment tensor "1e19,0,0,0,0,0 " implemented and documented.
