### ISSUE TITLE
1d reference models used

### ISSUE THREAD

**Issue by alexhutko** [iris-edu/irisws-syngine#21]
@sstaehler  Can you help us with simple text files of the reference models used for the current model catalog? thx

http://ds.iris.edu/ds/products/syngine/#models

**Comment by sstaehler** [comment]
[1d_models.zip](https://github.com/iris-edu/irisws-syngine/files/55343/1d_models.zip)
These are the models in the axisem input format. Python can read them with

```
import numpy as np
model_prem_ocean = np.loadtxt('1dmodel_PREM_ocean.txt', skiprows=6)
```

**Comment by martinvandriel** [comment]
I thought I changed the way the number of layers is computed in these outputs, why do you still have so many layers e.g. in the inner core?

https://github.com/geodynamics/axisem/commit/bb7025c265eeacd17c8dc171d8fb8af639be33a3

**Comment by alexhutko** [comment]
Will this affect the results, i.e. do any of the models need to be regenerated?

We have the 1d models in place ready to be made public once you approve that they are correct/valid.
http://ds.iris.edu/ds/products/emc-syngine

thanks.

**Comment by sstaehler** [comment]
@alexhutko 
No, @martinvandriel's comment was just about the number of layers in the 1D model file created by AxiSEM. Does not affect the databases at all.
The 1D models on the website look fine.
