### ISSUE TITLE
problem with durations?

### ISSUE THREAD

**Issue by alexhutko** [iris-edu/irisws-syngine#25]
Hi,

I found that syngine's maximum allowable duration of seismograms is =  dt \* (npts - (3*source_shift) + 1).  This means though we advertise 17999.6 s, we can only serve up traces that are 17953 s or less using the default settings.

Are there any objections to us changing the advertised database durations to reflect the effective duration?  Perhaps I should first ask if this should only be a syngine issue rather than instaseis.

Thanks,
Alex

PS: why 3xsource_shift and not 2x?

InstaseisDB reciprocal Green's function Database (v8) generated with these parameters:
    components           : vertical and horizontal
    velocity model       : prem_ani
    attenuation          : True
    dominant period      : 10.000 s
    dump type            : displ_only
    excitation type      : dipole
    time step            : 2.441 s
    sampling rate        : 0.410 Hz
    number of samples    : 7376
    seismogram length    : 17999.6 s
    source time function : gauss_0
    source shift         : 17.084 s
    spatial order        : 4
    min/max radius       : 5671.0 - 6371.0 km
    Planet radius        : 6371.0 km
    min/max distance     : 0.0 - 180.0 deg
    time stepping scheme : symplec4
    compiler/user        : gfortran 5.2.0 by productext on dpstage
    directory/url        : ../../axisem/MODELS/prem_a_10s
    size of netCDF files : 69.4 GB
    generated by AxiSEM version v1.2-31-g69d4-dirty at 2015-11-12T09:36:02.000000Z

**Comment by krischer** [comment]
Hi Alex,

the default duration is (to the closest included resampled samples):

`(database_npts - 1) * database_dt - src_shift - (kernel_width * database_dt)`

This is less than the length written in the `db.info` dictionary. You can still retrieve the full length by settings `dt` to the database `dt` (thus no resampling will happen) and carefully settings the `starttime` to`source shift` smaller then the `origintime` parameter. Users are most likely to change the `kernel_width` or the `dt` parameters which both influence the final retrieved length.

I'm fine with advertising the length of seismograms that will be retrieved with the default parameters but I'm also ok with the current way. So do as you see fit.

Cheers!

Lion
