### ISSUE TITLE
Internal Server Error with fuzzed POST request

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#26]
The following POST payload causes an internal server error with HTTP status code 500. I realize its not a valid request but that should raise another error.

```
model=test
format=saczip
eventid=GCMT:C201002270634A
IU ANMO LOCCODE=00
random things
help
```

**Comment by manoch-iris** [comment]
It is now responding correctly:

HTTP request sent, awaiting response... 400 Bad Request
2017-06-12 10:40:41 ERROR 400: Bad Request.
