### ISSUE TITLE
Small error in the POST request documentation

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#27]
It currently is written as

```
parameter=value
parameter=value
...
latitude longitude STACODE=<SYN> [NETCODE=XX] [LOCCODE=SE]
netcode stacode
...
```

The station code is also optional as I discovered from testing.

**Comment by alexhutko** [comment]
Thanks for catching this documenation discrepancy.  It was originally required and we changed it.  I've updated the doc.

**Comment by alexhutko** [comment]
> close
