### ISSUE TITLE
Some invalid lines in POST request are silently ignored

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#28]
The following POST payload return synthetics from three stations:

```
model=test
format=saczip
eventid=GCMT:C201002270634A
IU ANMO
14 15
IU ASDF LOCCODE=00
12 13
```

The third station line (which I realize is not valid) is silently ignored. I think it should at least show up in the produced log file. The current log file is:

```
RECEIVER lat:13.909930, lon:15, netcode:XX, stacode:S0001, STATUS OK
RECEIVER lat:11.921974, lon:13, netcode:XX, stacode:S0002, STATUS OK
RECEIVER lat:34.765424, lon:-106.4572, netcode:IU, stacode:ANMO, STATUS OK
```

**Comment by manoch-iris** [comment]
The "unrecognized request line" error message is now included in the log file:

ERROR: Unrecognized request line: 'IU ASDF LOCCODE=00'
