### ISSUE TITLE
Silent wildcards if network or station codes are not given

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#29]
I am not sure if this is intentional and from my point of view this is rather dangerous in the sense that it might result in lots of unintentional downloads. The following request for example will download the full `IU` network:

http://service.iris.edu/irisws/syngine/1/query?model=ak135f_5s&eventid=GCMT%3AC201002270634A&network=IU

**Comment by alexhutko** [comment]
Yes it is intentional.  It's consistent with our dataselect webservice where empty fields are wildcarded to help users make large requests, without having to know every station name.

**Comment by chad-earthscope** [comment]
as Alex said.
