### ISSUE TITLE
Content-Disposition HTTP Header

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#3]
In the case of zipped SAC files I think it is better to name it `*.zip` instead of `*.saczip`. Then double clicking on it should automatically unzip it on most platforms.

**Comment by CTrabant** [comment]
Agreed and .zip is the intended behavior for a release.  This is a low level issue of how the service is operated through a Web Service Shell.

**Comment by CTrabant** [comment]
Fixed.

> Content-Disposition: attachment; filename=syngine-prem_iso-2002-11-03t22:13:28.zip
> Content-Type: application/vnd.sac+zip
