### ISSUE TITLE
Less accurate error message

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#31]
Something changed server side and the error message when requesting invalid components changed from a specific and helpful one to a generic and less useful one.

Example request:

http://service.iris.edu/irisws/syngine/1/query?eventid=GCMT%3AC201002270634A&network=IU&format=miniseed&station=ANMO&components=ABC&model=ak135f_5s

Now returns:

```
Error 400:   handler exited, no error message from handler

More Details:
handler exited, code: 3  reason: Bad Request

Request:
http://service.iris.edu/irisws/syngine/1/query?eventid=GCMT%3AC201002270634A&network=IU&format=miniseed&station=ANMO&components=ABC&model=ak135f_5s

Request Submitted:
2016/05/24 17:26:58 UTC

Service version:
Service: irisws-syngine  version: 1.0.1
```

It used to have an error message containing the words "Unrecognized component" which IMHO is much more useful especially for routes that have a ton of parameters.

I just know this because ObsPy has a now failing test for this.

**Comment by megies** [comment]
See http://tests.obspy.org/41082/#5 and https://github.com/obspy/obspy/blob/95370bf7e8/obspy/clients/syngine/tests/test_client.py#L252-L265.

**Comment by chad-earthscope** [comment]
Issue has been tracked down.  Fixed is in testing and should be pushed to production soon, ideally this week.

**Comment by krischer** [comment]
This just came up again as we are releasing a new ObsPy version: The first time this URL is called, the error message is correct. Subsequent times its wrong. This can (sometimes?) be repeated if one waits a couple of minutes. Maybe some caching issue?

**Comment by CTrabant** [comment]
The fix is known but ended up being combined with a number of other issues that need resolving.  Its on the way.

**Comment by chad-earthscope** [comment]
The updated has been completed and this issue has been addressed.
