### ISSUE TITLE
Relative start and/or end times stopped working

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#33]
Dear all,

its seems relative start and/or end times stopped working. 

This is an example from the [syngine page](http://service.iris.edu/irisws/syngine/1) and it returns a code of 204:

http://service.iris.edu/irisws/syngine/1/query?network=_GSN&components=Z&eventid=GCMT:M110302J&starttime=P-10&endtime=ScS%2B60&format=saczip

**Comment by manoch-iris** [comment]
Dear Lion,

The issue is fixed. We were missing the newly introduced db_info parameter. Please note that syngine continues to use iasp91 model for relative start and/or end times. This will be changed to the "current model" travel times as soon as we roll in our system updates soon.

Thank you for pointing this out

**Comment by krischer** [comment]
Great! Thanks! I can confirm that it works again.

**Comment by krischer** [comment]
Hi guys,

I just realized that the phase relative time settings don't work with the test model, e.g. this does not work (identical to the one above but a different model):


http://service.iris.edu/irisws/syngine/1/query?network=_GSN&components=Z&eventid=GCMT:M110302J&starttime=P-10&endtime=ScS%2B60&format=saczip&model=test&nodata=404

**Comment by krischer** [comment]
I cannot reopen this issue - can one of you do it?

**Comment by manoch-iris** [comment]
Hi Lion,

The issue has been addressed. During the implementation of relative time the test model was not configured! I added the test model (prem_iso_light ) to the configuration to use PREM model for relative time computations. Thank you for bringing this to our attention.

**Comment by krischer** [comment]
Thanks for the fast fix!
