### ISSUE TITLE
CMPINC and CMPAZ?

### ISSUE THREAD

**Issue by ghayes-usgs** [iris-edu/irisws-syngine#39]
Can you add CMPINC and CMPAZ to the SAC headers of synthetics? They'd be extremely useful for (at least my) subsequent processing; at the moment I'm adding manually, but it seems like it should be fairly easy to add them on the front end...

**Comment by krischer** [comment]
Done in https://github.com/krischer/instaseis/pull/56

@ghayes-usgs: Would be great if you can review and check if the calculations and conventations are correct.

**Comment by manoch-iris** [comment]
Syngine is upgraded to instaseis 1.2.0 that supports CMPINC and CMPAZ and they now are included in SAC headers of synthetics
