### ISSUE TITLE
networkcode argument

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#4]
What is the motivation for offering a `stationcode` parameter but not a `networkcode` parameter? I guess you want to make clear that one is downloading synthetics?

In practice station codes are not unique so one also needs to set the network codes. The workflows of some people (and me) I've seen store the synthetics in a separate folder but give full ids which makes it easier to match it with actual data. Thus giving the option to also set the network code makes sense from my point of view.

**Comment by CTrabant** [comment]
We will expose the `networkcode` parameter.  After consulting with some network operators on how they felt about re-using their code we are more comfortable.  This is already in our middle ware, just need support in Instaseis.

**Comment by krischer** [comment]
Good to hear :-)

Instaseis already supports it.

**Comment by CTrabant** [comment]
I should have been more complete: this change was to enable both `networkcode` and `locationcode`.  It does not look like the locationcode change to Instaseis has been merged into the master branch yet:
https://github.com/krischer/instaseis/pull/12

**Comment by krischer** [comment]
I was waiting with the merge if it works for you. That seems to be given so I merged it.

**Comment by CTrabant** [comment]
Hm, didn't know you were waiting for review.  I'm not planning on testing branches in general if that's what you were waiting for.  Perhaps after release as we add more features, but now there are simply too many nooks and crannies to be branch-switching.

**Comment by CTrabant** [comment]
Support for `networkcode` and `locationcode` is now supported.

Note that `networkcode` and `stationcode` are ignored when `network` and `station` are specified.  The reason this should never work is wildcards would easily produce same-named synthetics.  The documentation has been updated to reflect this.

**Comment by krischer** [comment]
> Hm, didn't know you were waiting for review.

Reviews are of course always nice but I'm not expecting that ;-) A comment if the feature does what you want it to do would be helpful to organize our discussion.

> Note that networkcode and stationcode are ignored when network and station are specified. The reason this should never work is wildcards would easily produce same-named synthetics. The documentation has been updated to reflect this.

+1. That's also the behaviour of the instaseis /seismograms route.
