### ISSUE TITLE
Headers of /info route are off

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#5]
e.g. http://service.iris.edu/irisws/syngine/1/info?model=ak135f 
- Content type is `application/vnd.sac+zip`
- Content-Disposition is `inline; filename=irisws-syngine_2015-10-01T14:56:25.saczip`

**Comment by CTrabant** [comment]
Fixed.
- Cotent-Disposition is `Content-Disposition: inline; filename=syngine-ak135f-info.json`
- Content-Type is `application/json`
