### ISSUE TITLE
Gzip encoding for /info route

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#7]
Most of the space is needed for the zeros in the `/info` route. gzipping it compresses it down to almost nothing so its worth considering it here. The Instaseis server can do it so you could just forward it but I guess you have your own middleware to do that as well.

**Comment by CTrabant** [comment]
When the Content-Type is set correctly to `application/json` this will be resolved, as the container is already set to compress that type.

**Comment by CTrabant** [comment]
Fixed.  

Note that the client must specified that gzip encoding is acceptable in the request, i.e. with the Accept-Encoding header.  To make curl do this the header needs to be manually specified:

> curl --verbose -o out -H 'Accept-Encoding: gzip,deflate' 'http://service.iris.edu/irisws/syngine/1/info?model=ak135f'

...

> Content-Disposition: inline; filename=syngine-ak135f-info.json
> Content-Type: application/json
> Transfer-Encoding: chunked
> Content-Encoding: gzip

**Comment by krischer** [comment]
Minor nitpick: It does not work for the test model:

``` bash
curl --verbose -o out -H 'Accept-Encoding: gzip,deflate' 'http://service.iris.edu/irisws/syngine/1/info?model=test'
```

**Comment by krischer** [comment]
Implemented for the Instaseis syngine client in krischer/instaseis@e88429d4f6ab2ff50e5942e96029426efa2e3f9c

**Comment by krischer** [comment]
So the gzip encoding works as clearly less data is transferred but the latency is quite a bit bigger resulting in a longer total download time for the gzipped version which I would not expect. It might be an issue with your caching layer?

``` bash
time curl -s -o out -H 'Accept-Encoding: gzip,deflate' 'http://service.iris.edu/irisws/syngine/1/info?model=ak135f'
0.00s user 0.00s system 0% cpu 1.403 total

time curl -s -o out -H 'Accept-Encoding: gzip,deflate' 'http://service.iris.edu/irisws/syngine/1/info?model=ak135f'
0.00s user 0.00s system 0% cpu 1.413 total

time curl -s -o out -H 'Accept-Encoding: gzip,deflate' 'http://service.iris.edu/irisws/syngine/1/info?model=ak135f'
0.00s user 0.00s system 0% cpu 1.405 total

$ time curl -s -o out 'http://service.iris.edu/irisws/syngine/1/info?model=ak135f'
0.00s user 0.00s system 0% cpu 1.238 total

$ time curl -s -o out 'http://service.iris.edu/irisws/syngine/1/info?model=ak135f'
0.00s user 0.00s system 0% cpu 1.294 total

$ time curl -s -o out 'http://service.iris.edu/irisws/syngine/1/info?model=ak135f'
0.00s user 0.00s system 0% cpu 1.184 total
```

**Comment by CTrabant** [comment]
> Minor nitpick: It does not work for the test model:
> 
> curl --verbose -o out -H 'Accept-Encoding: gzip,deflate' 'http://service.iris.edu/irisws/syngine/1/info?model=test'

Apache Tomcat is doing the compression on the fly and is configured to not compress anything less than 2048 bytes.  This is the default for Tomcat because it is generally not worth it to compress such small things (given a balance between bandwidth and CPU cycles on either end). This do-not-compress-small-things is common in web ware.

**Comment by CTrabant** [comment]
> So the gzip encoding works as clearly less data is transferred but the latency is quite a bit bigger resulting in a longer total download time for the gzipped version which I would not expect. It might be an issue with your caching layer?

There is no caching layer, Apache Tomcat is compressing the output on the fly.  If you were on a slow network connection to IRIS the value of compression would be more apparent.  As it is these JSON documents are just on the boundary of where they become worth it to compress.

The difference at your location looks like ~0.2 seconds.  Hardly seems much bigger.  I suggest this is not worth worrying about.

**Comment by krischer** [comment]
Thanks for the clarifications!
