### ISSUE TITLE
Add tiny test database?

### ISSUE THREAD

**Issue by krischer** [iris-edu/irisws-syngine#8]
Hi guys,

would it possible to add the same test database we internally use for Instaseis to the syngine service? It could well be hidden to the normal user. It's only 4 MB large and the only purpose it serves is to internally test Instaseis. I'm writing a syngine client for Instaseis and this would make it trivial to test it. As a bonus it would test parts of the syngine service.

DB: https://github.com/krischer/instaseis/tree/master/instaseis/tests/data/100s_db_bwd_displ_only

Thanks!

Lion

**Comment by CTrabant** [comment]
Done.

The `100s_db_bwd_displ_only` model is available when `model=test`

**Comment by krischer** [comment]
Thanks for this!

Can you also add the test model to your `info` route?

http://service.iris.edu/irisws/syngine/1/info?model=test

**Comment by CTrabant** [comment]
Done.  Now a new shared configuration so that the query and info methods will never be out of sync.
